
apiVersion: v1
kind: Service
metadata:
  name: pbwear
  labels:
    app: pbwear
spec:
  ports:
    - port: 9080
  selector:
    app: pbwear
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: pbwear
  name: pbwear
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pbwear
    spec:
      containers:
      - image: mycluster.icp:8500/default/pbwear:latest
        name: pbwear
        ports:
        - containerPort: 9080
          protocol: TCP
